### ISSUE TITLE
Touch up game UI 

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#155]
Issues:
- [x] Concede game button is slightly too wide, causes right tools to overflow.
- [x] Gap between hand and fusion deck and hand and deck is asymmetric. Recommended change: Make hand/fusion deck gap smaller to match
- [x] On very specific smaller screen sizes, the right column of the playing field disappears.

**Comment by scheibo** [comment]
I think we need to attack this from first principles:

![](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model/boxmodel-(3).png)

The fundamental thing that all the sizing in the application is based upon is the **card** - everything else revolves around this. In particular, the card height, as we've defined the card width to be `Math.floor(height / CARD_RATIO)` where `CARD_RATIO` is 1.45. This alone isn't actually sufficient, because the card/card zone also has a 3px border, so the *true* height is `height + 6px` and the true width is `Math.floor(height / CARD_RATIO) + 6px`. Accounting for the border in particular is important because those little pixels are what caused the UI to get fucked up in the end :).

Height is passed into the battlefield indirectly as a prop called `size` which for reasons that are not clear to me at all is actually `cardHeight + 2`. I think we need to do away with the notion of "size", or at least redefine it so everything is defined in terms of card height. As it currently stands, the fact that `size` is not equal to `cardHeight` means that a **card in the hand is generally 2px larger than one on the field**, which is somewhat baffling (is this meant to reflect perspective because the cards are closer to the player? How was the number 2 chosen?). The card size in the hand might actually shrink further, as it will get multiplied by 0.95 if we have more than 7 cards in the hand (0.9 for the villain). 

Where does `size` (and thus `cardHeight`) come from? It is passed to `Battlefield` as `sizingValue / (5 + VILLAIN_HAND_SIZE)` where `VILLAIN_HAND_SIZE` is 0.5. 5 in this equation seems like it could have to do with the starting hand size, though its very unclear why we're adding 0.5 to it, and also why the starting hand size dictates things as opposed to perhaps 6 (the number of columns of cards across the field)? `sizeValue` comes from:

```js
const vpw = Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0);
const vph = Math.max(document.documentElement.clientHeight || 0, window.innerHeight || 0);
return Math.min(vpw / GAME_RATIO, vph);
```

Which also maybe seems a bit odd to me. Why are we taking max of clientWidth and innerWidth instead of min? Both of these purport to be a way of measuring viewport size, though one includes the scrollbar, which I don't think we want to include? I think perhaps both of these maxes should be changed to mins, but I guess that the `max` is do do away with 0 (just swap to `Infinity` if undefined instead)? The last line isn't clear to me either - where does 1.8 come from? What is this trying to do?

**I think we need to figure out from base principles how we define card height (and thus width) and label all these constants/add comments as appropriate**

---

Assuming we have a good way of calculating an appropriate card height, we can set to work on the rest.

Inside our container we have
- the left panel (currently 23%)
- the gameplay container (currently 77%)
  - the cards in play
  	- opponents hand
  	- the field
  	  - the left card column
  	  - 4 card rows
  	  - the right card column
  	- players hand
  - the right tools (currently 15%)

**We need to define our measurements somewhat inside out** - the field is what should determine the size of the the right and left tools. We mostly are constrained in width, not in height, so I won't really worry too much about the exact details of height right now. 

To simplify things, define `margin` to be the value required to make it so that we have enough space to turn cards into defense position, which is at LEAST their height. Ignore what the current code is doing,  this should be:

```js
const cardWidth = Math.floor(cardHeight * CARD_RATIO);

const borderedHeight = cardHeight + 6;
const borderedWidth = cardWidth + 6;

// TODO: should this actually be borderedWidth and borderedHeight?
const margin = Math.ceiling((height - width) / 2); // must be ceiling to guarantee we have at least enough space

const rowWidth = 5xborderedWidth + 5*(2*margin); // each card has a margin on each side
const columnWidth = borderedWidth + margin; // left column only needs a right margin, right column only needs a left margin

const fieldWidth = columnsWidth + rowWith + columnsWidth
```

This field width is the minimum size we need to accommodate all our cards. From this, we probably want to add a little bit of margin on either side so the left and right tools have some breathing room, and then we can try to get everything as close to the existing percentages as possible using `calc`

```js
const space = 3px; // or whatever
const comfyFieldWidth = fieldWidth + 2*space;
```

Hand width should just be = `rowWidth`, as this means it will stay `margin` away from either deck.

We now know the width of all the cards in play, so we need to figure out the right tools and left panel size. Given we want right tools to be ~15% of the gameplay container, we know the cards in play ie the `comfyFieldWidth` is 85% Furthermore, we know we want both of these things together to be ~77% of the full width. Thus:

```js
const minGamePlay = comfyFieldWidth/0.85; // ~15% right tools + field
const leftToolsWidth = min(23%, calc(100% - minGamePlay));
const gamePlayWidth = calc(100% - leftToolsWidth);
const rightToolsWidth = min(15%, gamePlayWidth*0.15); // or something like that
```

Please check my math/make sure you follow along. we might also need to add some padding/margins to some of the minimums in some places to make sure things dont get too cramped, but i think the base equations should hold.

**Comment by acpennington** [comment]
I just wanted to let you know that I am not ignoring your comment. I have the answer to most of these questions, but I don't want to spend all day at work answering them in detail. It would probably be better to schedule a time on the weekend for us to go over it in detail (on discord), assuming that we can find time when we are both available.

Note: While you are thinking of the math in terms of the inside out, I actually think of it terms of the outside in. That is, I figured out what size that I wanted the game/battlefield to be first, and then figured out the card sizes based on that,
