### ISSUE TITLE
Add more complicated prepopLP paramaters

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#225]
With cards like Just Desserts and D.D. Dynamite, it should be possible to use the gamestate to calculate damage.

**Comment by scheibo** [comment]
I think it would be nice if we prioritized this. I imagine there would actually be quite a few of these needed, and they would be kind of as complex as scripts. We basically need to run a function `calculatePrepopLP(state)` whenever the card is clicked. I think that since these complex prepopLP's are going to be the minority, the current form of `prepopLP` with just hero/villain should be preserved so as to not make the simple cases more complicated. From the cards we've already flagged, I think we would need the following:

- ~~**Just Desserts:** `prepopLP: {villain: { script: VILLAIN_MONSTER, params: { multiplier: -500  } } }`~~
- ~~**D.D. Dynamite:** `prepopLP: {villain: { script: VILlAIN_BANISHED, params: { multiplier: -300  } } }`~~
- ~~**Gift of the Mystical Elf:** `prepopLP: {hero: { script: FIELD_MONSTER, params: { multiplier: 300  } } }`~~
- ~~**Restructer Revolution:** `prepopLP: {villain: { script: VILLAIN_HAND, params: { multiplier: -200  } } }`~~
- ~~**Solar Ray:** `prepopLP: {villain: { script: HERO_MONSTER, params: { attribute: { value: "Light" }, set: false, multiplier: -600  } } }`~~
- ~~**The Spell Absorbing Life:** `prepopLP: {hero: { script: FIELD_MONSTER, params: { cardType: { value: "effectMonster" }, multiplier: 400  } } }`~~
- ~~**Balloon Lizard:** `prepopLP: {villain: { script: COUNTER, params: { multiplier: -400  } } }`~~
- ~~**White Magician Pikeru:** `prepopLP: {hero: { script: HERO_MONSTER, params: { multiplier: 400  } } }`~~
- ~~**Wave-Motion Cannon:** `prepopLP: {villain: { script: COUNTER, params: { multiplier: -1000  } } }` (just make the user add counters, this is probably how they would track the turns anyway)~~
- ~~**Ceasefire:** `prepopLP: {villain: { script: FIELD_MONSTER, params: { cardType: { value: "effectMonster" }, multiplier: -500  } } }`~~
- ~~**Secret Barrel:** `prepopLP: {villain: { script: VILLAIN_HAND_AND_FIELD, params: { multiplier: -200  } } }`~~
- ~~**Des Koala:** `prepopLP: {villain: { script: VILLAIN_HAND, params: { multiplier: -400  } } }`~~
