### ISSUE TITLE
Make when/if follow PSCT conventions

### ISSUE THREAD

**Issue by acpennington** [acpennington/GoatController#273]
For trigger and trigger-like effects:
- If they are mandatory they should always say "If"
- If they are optional, they can say "When" or "If" depending on if timing can be missed or not (usually, they will say "When", which indicates that they CAN miss timing).

For continuous and continuous-like effects:
- Always use "When" to specify timing, never "If." For example, Call of the Haunted's two continuous-like effects should say "When."

All other spell/trap effects:
- For specifying timing that the card can be activated, always use "When." For example, Sakuretsu Armor should read, "When an opponent's monster..."

**Comment by scheibo** [comment]
I don't know if theres a more sophisticated way of doing this than doing a find for `If` and replace for `When` and then stepping through each in VS Code to evaluate whether the `If` was added erroneously or not.

I also ran a check for `card.text.includes("If") && !card.text.includes("Trigger")`, these are the 133 results:

---

- **3-Hump Lacooda**: Beast/Effect – <effect=Ignition>If you control 3 "3-Hump Lacooda": You can Tribute 2 of them; draw 3 cards.</effect>
- **A Deal with Dark Ruler**: (This card is always treated as an "Archfiend" card.) If a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.
- **A Hero Emerges**: If an opponent's monster declares an attack: Your opponent chooses 1 random card from your hand, then if it is a monster that can be Special Summoned, Special Summon it. Otherwise, send it to the Graveyard.
- **Abare Ushioni**: Beast-Warrior/Effect – <effect=Ignition>Once per turn: You can toss a coin and call it. If you call it right, inflict 1000 damage to your opponent. If you call it wrong, take 1000 damage.</effect>
- **Adhesion Trap Hole**: If your opponent Summons a monster(s): Halve that monster(s)'s original ATK.
- **Amazoness Archers**: If an opponent's monster declares an attack, while you control an "Amazoness" monster: Change all monsters your opponent currently controls to face-up Attack Position (Flip monsters' effects are not activated at this time), they lose 500 ATK, also they must attack this turn, if able.
- **Amphibious Bugroth MK-3**: Machine/Effect – <effect=Continuous>If "Umi" is on the field, this card can attack your opponent's Life Points directly.</effect>
- **Amplifier**: <effect=Condition>Equip only to "Jinzo".</effect> <effect=Continuous-like>This card's activation and effect cannot be negated.</effect> <effect=Continuous-like>The equipped monster's effect, "Traps, and their effects on the field, cannot be activated. Negate all Trap effects on the field." becomes "Your opponent cannot activate Traps, or their effects on the field. Negate all Trap effects your opponent controls."</effect> <effect=Condition>If this card leaves the field, destroy the equipped monster.</effect>
- **Ancient Gear Beast**: Machine/Effect – <effect=Summon>Cannot be Special Summoned.</effect> <effect=Continuous>If this card attacks, your opponent cannot activate any Spells/Traps until the end of the Damage Step.</effect> <effect=Continuous>Negate the effects of an opponent's monster destroyed by battle with this card (including in the Graveyard).</effect>
- **Ancient Gear Golem**: Machine/Effect – <effect=Summon>Cannot be Special Summoned.</effect> <effect=Continuous>If this card attacks, your opponent cannot activate any Spells/Traps until the end of the Damage Step.</effect> <effect=Continuous>If this card attacks a Defense Position monster, inflict piercing battle damage.</effect>
- **Ancient Gear Soldier**: Machine/Effect – <effect=Continuous>If this card attacks, your opponent cannot activate any Spells/Traps until the end of the Damage Step.</effect>
- **Ante**: Each Player reveals 1 card from their hand. If one card is higher Level than the other, the card with the lower Level is sent to the Graveyard, and the player who revealed it takes 1000 damage. (Non-Monster Cards are treated as Level 0).
- **Anti Raigeki**: If your opponent activates "Raigeki": Negate its effect, and if you do, destroy all monsters your opponent controls.
- **Anti-Spell**: If a Spell is activated: Remove 2 Spell Counters from your field; negate its activation, and if you do, destroy it.
- **Arcane Archer of the Forest**: Warrior/Effect – <effect=Continuous>If you control a Plant monster, this card cannot be attacked.</effect> <effect=Ignition>You can Tribute 1 Plant monster, then target 1 Spell/Trap on the field; destroy that target.</effect>
- **Armor Break**: If an Equip Spell is activated: Negate its activation, and if you do, destroy it.
- **Armored Glass**: If a monster is equipped with an Equip Card: Negate all Equip Cards effects on the field this turn.
- **Array of Revealing Light**: <effect=Continuous-like>If this card is activated, declare 1 Type of monster. Monsters of the declared Type cannot declare an attack during the turn they are Summoned.</effect>
- **Arsenal Bug**: Insect/Effect – <effect=Continuous>If you control no other Insect monsters, this card's ATK/DEF become 1000.</effect>
- **Attack and Receive**: If you take damage: Your opponent takes 700 damage, also they take 300 damage for each "Attack and Receive" in your Graveyard.
- **Autonomous Action Unit**: Pay 1500 Life Points, then target 1 monster in your opponent's Graveyard; Special Summon that target on your field in face-up Attack Position, and equip it with this card. <effect=Continuous-like>If this card leaves the field, destroy the equipped monster.</effect>
- **Bait Doll**: Target 1 Set card in the Spell & Trap Zone; reveal that target, force its activation if it is a Trap, then negate its effect if the activation timing is incorrect, and if you do, destroy it. (If it is not a Trap, return it face-down.) If this card resolves, shuffle it into the Deck instead of sending it to the Graveyard.
- **Ballista of Rampart Smashing**: <effect=Continuous-like>If the equipped monster attacks a face-down Defense Position monster, it gains 1500 ATK during damage calculation only.</effect>
- **Bark of Dark Ruler**: If a Fiend monster you control battles, during the Damage Step: Pay Life Points (in multiples of 100 points), then target the opponent's battling monster; that opponent's monster loses that much ATK/DEF, until the end of this turn.
- **Barrel Behind the Door**: If a card or effect is activated that would inflict damage to your Life Points: Your opponent takes the damage instead.
- **Batteryman AA**: Thunder/Effect – <effect=Continuous>If all "Batteryman AA"(s) you control are in Attack Position, this card gains 1000 ATK for each.</effect> <effect=Continuous>If all "Batteryman AA"(s) you control are in Defense Position, this card gains 1000 DEF for each.</effect>
- **Battle-Scarred**: <effect=Continuous-like>Target 1 "Archfiend" monster you control to activate this card. Your opponent also pays the same Life Points that you pay for the targeted monster during the Standby Phase.</effect> <effect=Continuous-like>If this card leaves the field, destroy the targeted monster.</effect> <effect=Continuous-like>If the targeted monster leaves the field, destroy this card.</effect>
- **Berserk Gorilla**: Beast/Effect – <effect=Continuous>If this card is in face-up Defense Position, destroy this card.</effect> <effect=Continuous>This card must attack if able.</effect>
- **Big Bang Shot**: <effect=Continuous-like>The equipped monster gains 400 ATK.</effect> <effect=Continuous-like>If the equipped monster attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect> <effect=Continuous-like>If this card leaves the field, banish the equipped monster.</effect>
- **Big Burn**: If your opponent activates a card that targets a monster(s) in the Graveyard: Banish all monsters in both players' Graveyards.
- **Big Shield Gardna**: Warrior/Effect – <effect=Quick>If a Spell is activated that targets this face-down card (and no other cards): Change this card to face-up Defense Position, and if you do, negate the activation.</effect> <effect=Continuous>If this card is attacked, change it to Attack Position at the end of the Damage Step.</effect>
- **Black Tyranno**: Dinosaur/Effect – <effect=Continuous>If the only cards your opponent controls are Defense Position monsters, this card can attack your opponent directly.</effect>
- **Blade Knight**: Warrior/Effect – <effect=Continuous>While you have 1 or less cards in your hand, this card gains 400 ATK.</effect> <effect=Continuous>If you control no other monsters, the effects of Flip monsters destroyed by battle with this card are negated.</effect>
- **Blast Held by a Tribute**: If an opponent's monster that was Tribute Summoned declares an attack: Destroy as many face-up Attack Position monsters they control as possible, and if you do, inflict 1000 damage to your opponent.
- **Blasting the Ruins**: If there are at least 30 cards in your Graveyard: Your opponent takes 3000 damage.
- **Blue-Eyes Shining Dragon**: Dragon/Effect – <effect=Summon>Cannot be Normal Summoned/Set.</effect> <effect=Summon>Must be Special Summoned by Tributing 1 "Blue-Eyes Ultimate Dragon".</effect> <effect=Continuous>Gains 300 ATK for each Dragon monster in your Graveyard.</effect> <effect=Quick>If a card or effect is activated that targets this card: You can negate that effect.</effect>
- **Blue-Eyes Toon Dragon**: Dragon/Toon/Effect – <effect=Summon>Cannot be Normal Summoned/Set.</effect> <effect=Summon>Must first be Special Summoned (from your hand) by Tributing 2 monsters, while you control "Toon World".</effect> <effect=Continuous>Cannot attack the turn it is Special Summoned.</effect> <effect=Continuous>You must pay 500 Life Points to declare an attack with this monster.</effect> <effect=Continuous>If "Toon World" on the field is destroyed, destroy this card.</effect> <effect=Continuous>Can attack your opponent directly, unless they control a Toon monster, in which case this card must target a Toon monster for its attacks.</effect>
- **Bottomless Trap Hole**: If your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it.
- **Bubble Crash**: If a player(s) has at least 6 total cards in their hand and/or field: that player(s) sends cards from their hand and/or field to the Graveyard so the remaining amount of cards on their field and/or hand is 5.
- **Burst Stream of Destruction**: If you control "Blue-Eyes White Dragon": Destroy all monsters your opponent controls. "Blue-Eyes White Dragon" you control cannot attack the turn you activate this card.
- **Buster Rancher**: <effect=Condition>Equip only to a monster with 1000 or less ATK.</effect> <effect=Continuous-like>If the equipped monster's ATK becomes higher than 1000 other than because of this card's effect, destroy this card. During damage calculation only, the equipped monster gains 2500 ATK if the opponent's battling monster is in Attack Position and its ATK is 2500 or more, OR if the opponent's battling monster is in Defense Position and its DEF is 2500 or more.</effect>
- **Call of the Grave**: If your opponent activates "Monster Reborn": Negate the effect of that "Monster Reborn".
- **Call of the Haunted**: Activate this card by targeting 1 monster in your Graveyard; Special Summon that target in Attack Position. <effect=Continuous-like>If this card leaves the field, destroy that monster.</effect> <effect=Continuous-like>If that monster is destroyed, destroy this card.</effect>
- **Cannonball Spear Shellfish**: Aqua/Effect – <effect=Continuous>If "Umi" is on the field, this card is unaffected by Spell effects.</effect>
- **Catnipped Kitty**: Beast/Effect – <effect=Continuous>If you control another Beast monster(s), monsters your opponent controls cannot target this card for an attack.</effect> <effect=Ignition>Once per turn: You can target 1 face-up monster your opponent controls; its DEF becomes 0 until the end of this turn.</effect>
- **Ceasefire**: If a face-down Defense Position monster or an Effect Monster is on the field: Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip monsters' effects are not activated at this time), also inflict 500 damage to your opponent for each Effect Monster on the field.
- **Chaos End**: If at least 7 of your cards are banished: Destroy all monsters on the field.
- **Chaos Greed**: If at least 4 of your cards are banished and there are no cards in your Graveyard: Draw 2 cards.
- **Collected Power**: Target 1 face-up monster on the field; equip it with all Equip Cards on the field. <effect=Condition>If any of those Equip Cards is now equipped to an incorrect target, destroy that Equip Card.</effect>
- **Command Knight**: Warrior/Effect – <effect=Continuous>All Warrior monsters you control gain 400 ATK.</effect> <effect=Continuous>If you control another monster, monsters your opponent controls cannot target this card for an attack.</effect>
- **Continuous Destruction Punch**: <effect=Continuous-like>If a monster your opponent controls battled a Defense Position monster you control, after damage calculation destroy the attacking monster if its ATK is lower than the DEF of your monster.</effect>
- **Contract with Exodia**: If you have all 5 of "Exodia the Forbidden One", "Right Arm of the Forbidden One", "Left Arm of the Forbidden One", "Right Leg of the Forbidden One", and "Left Leg of the Forbidden One" in your Graveyard: Special Summon 1 "Exodia Necross" from your hand.
- **Creeping Doom Manta**: Fish/Effect – <effect=Continuous>If Normal Summoned, Traps cannot be activated.</effect>
- **Cross Counter**: If a monster your opponent controls attacks a Defense Position monster you control, and its DEF is higher than the attacking monster's ATK: Inflict double battle damage to your opponent, then destroy the attacking monster after damage calculation.
- **Curse of Royal**: If a Spell/Trap is activated that includes the effect of destroying exactly 1 Spell/Trap: Negate its activation, and if you do, destroy it.
- **Cursed Seal of the Forbidden Spell**: If a Spell is activated: Discard 1 Spell; negate the activation, and if you do, destroy it, and if you do that, your opponent cannot activate Spells with that name for the rest of this Duel.
- **Cyclon Laser**: <effect=Condition>Equip only to "Gradius".</effect> <effect=Continuous-like>It gains 300 ATK.</effect> <effect=Continuous-like>If the equipped monster attacks a Defense Position monster, inflict piercing damage to your opponent.</effect>
- **D.D. Designator**: Declare 1 card name. Look at your opponent's hand, and if they have the declared card in their hand, banish that 1 card. If they do not have the declared card in their hand, banish 1 random card in your hand.
- **Dark Driceratops**: Dinosaur/Effect – <effect=Continuous>If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Dark Magic Attack**: If you control "Dark Magician": Destroy all Spells/Traps your opponent controls.
- **Dark Mirror Force**: If an opponent's monster declares an attack: Banish all Defense Position monsters your opponent controls.
- **Dark Spirit of the Silent**: If an opponent's monster declares an attack: Target the attacking monster, negate the attack, and target another face-up monster your opponent controls; force it to attack instead. (If it is in face-up Defense Position, change it to Attack Position).
- **Dark-Piercing Light**: If your opponent controls a face-down Defense Position monster(s): Change all face-down Defense Position monsters your opponent controls to face-up Defense Position.
- **De-Spell**: Target 1 face-up Spell, or 1 Set Spell/Trap, on the field; destroy that target if it is a Spell. (If the target is Set, reveal it).
- **Deepsea Warrior**: Warrior/Effect – <effect=Continuous>If "Umi" is on the field, this card is unaffected by Spell effects.</effect>
- **Delta Attacker**: If you control 3 Normal Monsters with the same name (except Tokens): This turn, those monsters can attack directly.
- **Desert Sunlight**: If you control a face-down Defense Position monster(s) or face-up Attack Position monster(s): Change all monsters you control to face-up Defense Position.
- **Destruction Punch**: If a monster you control is attacked by a monster whose ATK is lower than your monster's DEF: Destroy the attacking monster at the end of the Damage Step.
- **Different Dimension Gate**: Activate this card by targeting 1 monster on each field; banish those targets. If this card is destroyed and sent to the Graveyard: Return those banished monsters to the field in the same battle positions they were in.
- **Diffusion Wave-Motion**: If your opponent controls a monster: Pay 1000 Life Points, then target 1 Level 7 or higher Spellcaster monster you control; this turn, it must attack all monsters your opponent controls once each, also other monsters you control cannot attack. The effects of monsters destroyed by these attacks cannot activate and are negated.
- **Dimension Distortion**: If there are no cards in your Graveyard: Target 1 of your banished monsters; Special Summon it.
- **Divine Wrath**: If a monster effect is activated: Discard 1 card; negate the activation, and if you do, destroy that monster.
- **Dragon's Gunfire**: If you control a Dragon monster: Activate 1 of these effects. ● Inflict 800 damage to your opponent. ● Target 1 monster with 800 or less DEF; destroy that target.
- **Dragon's Rage**: <effect=Continuous-like>If a Dragon monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Draining Shield**: If an opponent's monster declares an attack: Target the attacking monster; negate that attack, and if you do, gain Life Points equal to that target's ATK.
- **Dramatic Rescue**: If an effect is activated that targets an "Amazoness" monster on the field: Return the targeted monster to the hand, and if you do, Special Summon 1 monster from your hand, except the targeted monster.
- **Drillago**: Machine/Effect – <effect=Continuous>If the only cards your opponent controls are face-up monsters with 1600 or more ATK, this card can attack your opponent directly.</effect>
- **Driving Snow**: If a Trap(s) you control is destroyed by an opponent's card effect and sent from the field to the Graveyard: Target 1 Spell/Trap on the field; destroy that target.
- **Eagle Eye**: Winged Beast/Effect – <effect=Continuous>If Normal Summoned, Traps cannot be activated.</effect>
- **Eatgaboon**: If your opponent Normal or Flip Summons a monster with 500 or less ATK: Target that face-up monster; destroy that target.
- **Elegant Egotist**: If "Harpie Lady" is on the field: Special Summon 1 "Harpie Lady" or "Harpie Lady Sisters" from your hand or Deck.
- **Enraged Battle Ox**: Beast-Warrior/Effect – <effect=Continuous>If a Beast, Beast-Warrior, or Winged Beast monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Exodia the Forbidden One**: Spellcaster/Effect – <effect=Condition>If you have "Right Leg of the Forbidden One", "Left Leg of the Forbidden One", "Right Arm of the Forbidden One" and "Left Arm of the Forbidden One" in addition to this card in your hand, you win the Duel.</effect>
- **Fake Trap**: If your opponent activates a card or effect that would destroy a Trap(s) you control: Destroy this card instead of that Trap(s). (Reveal all of your face-down Traps that would have been destroyed).
- **Fatal Abacus**: <effect=Continuous-like>If a monster(s) is sent from the field to the Graveyard: Inflict 500 damage per card to its owner.</effect>
- **Fiend Comedian**: Toss a coin and call it. If you call it right, banish all cards from your opponent's Graveyard. If you call it wrong, send cards from the top of your Deck to the Graveyard equal to the number of cards in your opponent's Graveyard.
- **Fiend's Hand Mirror**: If your opponent activates a Spell that targets exactly 1 Spell/Trap (and no other cards) on the field: Target another card that would be an appropriate target; that Spell now targets the new target.
- **Goblin Attack Force**: Warrior/Effect – <effect=Continuous>If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the end of your next turn.</effect>
- **Gravekeeper's Spear Soldier**: Spellcaster/Effect – <effect=Continuous>If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Graverobber**: Target 1 Spell in your opponent's Graveyard; add it to your hand. If you use it, take 2000 damage immediately after. During the end phase, if you did not use it, send it to the Graveyard.
- **Gyaku-Gire Panda**: Beast/Effect – <effect=Continuous>Gains 500 ATK for each monster your opponent controls.</effect> <effect=Continuous>If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Injection Fairy Lily**: Spellcaster/Effect – <effect=Quick>If this card attacks or is attacked, during damage calculation (in either player's turn): You can pay 2000 Life Points once per battle; this card gains 3000 ATK during that damage calculation only.</effect>
- **Invasion of Flames**: Pyro/Effect – <effect=Continuous>If Normal Summoned, Traps cannot be activated.</effect>
- **Last Will**: If a monster you control is sent to your Graveyard, but only the first time after this card's activation: <effect=Lingering>You can Special Summon 1 monster with 1500 or less ATK from your Deck.</effect>
- **Light of Intervention**: <effect=Continuous-like>While this card is on the field, Monster Cards cannot be Set or flipped face-down.</effect> <effect=Continuous-like>If a Monster Card would be Set, it must be Normal Summoned in face-up Defense Position.</effect>
- **Mad Sword Beast**: Dinosaur/Effect – <effect=Continuous>If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent.</effect>
- **Magic Cylinder**: If an opponent's monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK.
- **Magic Jammer**: If a Spell is activated: Discard 1 card; negate the activation, and if you do, destroy it.
- **Metalmorph**: Target 1 face-up monster on the field; equip this card to that target. <effect=Continuous-like>It gains 300 ATK/DEF.</effect> <effect=Continuous-like>If it attacks, it gains ATK equal to half the ATK of the attack target, during damage calculation only.</effect>
- **Metalsilver Armor**: <effect=Continuous-like>If you control the equipped monster, your opponent cannot activate cards or effects that target exactly 1 monster, except the equipped monster.</effect>
- **Meteor of Destruction**: If your opponent's Life Points are higher than 3000: Inflict 1000 damage to your opponent.
- **Mirror Force**: If an opponent's monster declares an attack: Destroy all your opponent's Attack Position monsters.
- **My Body as a Shield**: If your opponent activates a Spell/Trap or monster effect that would destroy a monster(s) on the field: Pay 1500 Life Points; negate the activation, and if you do, destroy it.
- **Needle Ceiling**: If there are 4 or more monsters on the field: Destroy all face-up monsters.
- **Penalty Game!**: If your opponent has 4 cards in their hand: Activate 1 of these effects. ● Your opponent cannot draw during their next Draw Phase. ● Your opponent cannot activate Spells/Traps this turn.
- **Premature Burial**: Activate this card by paying 800 Life Points, then target 1 monster in your Graveyard; Special Summon that target in Attack Position and equip it with this card. <effect=Continuous-like>If this card is destroyed, destroy the equipped monster.</effect>
- **Pyramid of Light**: <effect=Continuous-like>If this face-up card leaves the field, destroy "Andro Sphinx" and "Sphinx Teleia" on your field, and if you do, banish them.</effect>
- **Reasoning**: Your opponent declares a monster Level from 1 to 12. Excavate cards from the top of your Deck until you excavate a monster that can be Normal Summoned/Set, then, if that monster is the same Level as the one declared by your opponent, send all excavated cards to the Graveyard. If not, Special Summon the excavated monster, also send the remaining cards to the Graveyard.
- **Reversal Quiz**: Send all cards from your hand and your field to the Graveyard, then call Spell, Trap, or Monster; reveal the top card of your Deck. If you called it right, both players exchange Life Points.
- **Rocket Jumper**: Rock/Effect – <effect=Continuous>If your opponent only controls Defense Position monsters, this card can attack directly.</effect>
- **Royal Oppression**: <effect=Quick-like>If a monster would be Special Summoned or an effect that Special Summons a monster(s) is activated (except during Damage Step): Either player may pay 800 Life Points; negate the Summon or activation, and if you do, destroy that card.</effect>
- **Sakuretsu Armor**: If an opponent's monster declares an attack: Target the attacking monster; destroy that target.
- **Serial Spell**: If you activate a Normal Spell: Discard all cards in your hand to the Graveyard; the effect of this card becomes the same as that Normal Spell.
- **Seven Tools of the Bandit**: If a Trap is activated: Pay 1000 Life Points; negate the activation, and if you do, destroy it.
- **Shadow Spell**: <effect=Continuous-like>Activate this card by targeting 1 face-up monster your opponent controls; it loses 700 ATK, also it cannot attack or change its battle position.</effect> <effect=Continuous-like>If it leaves the field, destroy this card.</effect>
- **Shadowslayer**: Fiend/Effect – <effect=Continuous>If all monsters your opponent controls are in Defense Position, this card can attack directly.</effect>
- **Solemn Judgment**: If a monster(s) would be Summoned, OR a Spell/Trap is activated: Pay half your Life Points; negate the Summon or activation, and if you do, destroy that card.
- **Spell Shield Type-8**: Activate 1 of these effects; ● If a Spell is activated that targets exactly 1 monster on the field: Negate the activation, and if you do, destroy it. ● If a Spell is activated: Send 1 Spell from your hand to the Graveyard; negate the activation, and if you do, destroy it.
- **Spellbinding Circle**: <effect=Continuous-like>Activate this card by targeting 1 monster your opponent controls; it cannot attack or change its battle position.</effect> <effect=Continuous-like>If that monster is destroyed, destroy this card.</effect>
- **Stamping Destruction**: If you control a Dragon monster: Target 1 Spell/Trap on the field; destroy that target, and if you do, inflict 500 damage to its controller.
- **Swift Gaia the Fierce Knight**: Warrior/Effect – <effect=Summon>If this is the only card in your hand, you can Normal Summon it without Tributing.</effect>
- **Swords of Concealing Light**: <effect=Condition>Destroy this card during your 2nd Standby Phase after activation.</effect> If this card resolves, change all monsters your opponent controls to face-down Defense Position. <effect=Continuous-like>Monsters your opponent controls cannot change their battle positions.</effect>
- **Swords of Revealing Light**: <effect=Condition>After this card's activation, it remains on the field, but you must destroy it during the End Phase of your opponent's 3rd turn.</effect> If this card is activated: If your opponent controls a face-down monster, flip all monsters they control face-up. <effect=Continuous-like>While this card is face-up on the field, your opponent's monsters cannot declare an attack.</effect>
- **Tactical Espionage Expert**: Warrior/Effect – <effect=Continuous>If Normal Summoned, Traps cannot be activated.</effect>
- **The Fiend Megacyber**: Warrior/Effect – <effect=Summon>If your opponent controls at least 2 more monsters than you do, you can Special Summon this card (from your hand).</effect>
- **The Spell Absorbing Life**: If a face-down Defense Position monster or an Effect Monster is on the field: Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip monsters' effects are not activated at this time), also gain 400 Life Points for each Effect Monster on the field.
- **Thousand-Eyes Restrict**: Spellcaster/Fusion/Effect – "Relinquished" + "Thousand-Eyes Idol". <effect=Continuous>Other monsters on the field cannot change their battle positions or attack.</effect> <effect=Ignition>Once per turn: You can target 1 monster your opponent controls; equip that target to this card (max. 1). This card must be face-up on the field to activate and to resolve this effect.</effect> <effect=Continuous>This card's ATK/DEF become equal to that equipped monster's. If this card would be destroyed by battle, destroy that equipped monster instead.</effect>
- **Thunder Nyan Nyan**: Thunder/Effect – <effect=Continuous>If you control a non-LIGHT monster, destroy this card.</effect>
- **Toon Cannon Soldier**: Machine/Toon/Effect – <effect=Continuous>Cannot attack the turn it is Summoned.</effect> <effect=Continuous>If "Toon World" on the field is destroyed, destroy this card.</effect> <effect=Continuous>While you control "Toon World" and your opponent controls no Toon monsters, this card can attack directly.</effect> <effect=Ignition>You can Tribute 1 monster; inflict 500 damage to your opponent.</effect>
- **Torrential Tribute**: If a monster(s) is Summoned: Destroy all monsters on the field.
- **Tragedy**: If a face-up Attack Position monster(s) your opponent controls is changed to face-up Defense Position: Destroy all Defense Position monsters your opponent controls.
- **Twin-Headed Wolf**: Fiend/Effect – <effect=Continuous>If you control another Fiend, negate the effects of Flip monsters destroyed by battle with this card.</effect>
- **Widespread Ruin**: If an opponent's monster declares an attack: Destroy the Attack Position monster your opponent controls with the highest ATK (your choice, if tied).

**Comment by scheibo** [comment]
Please see #275 for an automatic fix for those added by #260. I will do a follow up to revert #265 and #272.
